"""Write a Table of Contents for the wiki and for the internal docs.

Every page under each folder, in reading order, with its sections. Reading
order is the order pages are first reached by following links from the
folder's README, breadth first — so the contents read the way the index does,
and a page added to the index lands where it was put. A page nothing links to
still appears, at the end of its folder.

Run with `make toc` after adding, renaming or restructuring a page.
"""

from __future__ import annotations

import re
import sys
from collections import deque
from pathlib import Path
from urllib.parse import quote, unquote

DOCS = Path(__file__).resolve().parent.parent / "docs"
OUT = "Table of Contents.md"
BOOKS = {
    DOCS / "wiki": "Pamphlets User Wiki",
    DOCS / "internal": "Internal Documentation",
}

LINK = re.compile(r"\]\(([^)\s#]+)(?:#[^)\s]*)?\)")
FENCE = re.compile(r"```.*?```", re.S)


def prose(page: Path) -> str:
    """The page without its code blocks, where a `#` is not a heading."""
    return FENCE.sub("", page.read_text(encoding="utf-8"))


def slug(heading: str) -> str:
    """The anchor GitHub and most viewers give a heading."""
    plain = re.sub(r"[^\w\- ]", "", heading.strip().lower())
    return plain.replace(" ", "-")


def headings(page: Path) -> tuple[str, list[tuple[str, str]]]:
    """The page's title, and its sections with their anchors."""
    title = page.stem
    sections: list[tuple[str, str]] = []
    seen: dict[str, int] = {}
    for level, text in re.findall(r"^(#{1,6})\s+(.*?)\s*#*\s*$", prose(page), re.M):
        anchor = slug(text)
        count = seen.get(anchor, 0)
        seen[anchor] = count + 1
        if count:
            anchor = f"{anchor}-{count}"
        if level == "#" and title == page.stem:
            title = text
        elif level == "##":
            sections.append((text, anchor))
    return title, sections


def reading_order(root: Path) -> list[Path]:
    """Every page under `root`, in the order the index leads to them."""
    every = sorted(
        page for page in root.rglob("*.md")
        if page.name != OUT and "node_modules" not in page.parts
    )
    known = set(every)
    start = root / "README.md"
    order: list[Path] = []
    queue = deque([start])
    seen = {start}
    while queue:
        page = queue.popleft()
        order.append(page)
        for target in LINK.findall(prose(page)):
            if target.startswith(("http://", "https://", "mailto:")):
                continue
            found = (page.parent / unquote(target)).resolve()
            if found in known and found not in seen:
                seen.add(found)
                queue.append(found)
    return order + [page for page in every if page not in seen]


def link(root: Path, page: Path, anchor: str = "") -> str:
    path = quote(page.relative_to(root).as_posix(), safe="/")
    return f"{path}#{anchor}" if anchor else path


def contents(root: Path, name: str) -> str:
    pages = reading_order(root)
    folders: dict[Path, list[Path]] = {}
    for page in pages:
        folders.setdefault(page.parent, []).append(page)

    lines = [
        f"# Table of Contents — {name}",
        "",
        "Every page and its sections, in reading order. Generated by `make toc`; edit the pages, "
        "not this file.",
        "",
    ]
    for folder, inside in folders.items():
        heading = "Overview" if folder == root else folder.relative_to(root).as_posix()
        lines += [f"## {heading}", ""]
        for page in inside:
            title, sections = headings(page)
            lines.append(f"- [{title}]({link(root, page)})")
            lines += [
                f"  - [{text}]({link(root, page, anchor)})" for text, anchor in sections
            ]
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    for root, name in BOOKS.items():
        written = contents(root, name)
        (root / OUT).write_text(written, encoding="utf-8")
        print(f"wrote {root.relative_to(DOCS.parent) / OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
